<?php
/**
 * Created by PhpStorm.
 * User: MonkeyKing
 * Date: 16-Mar-19
 * Time: 3:08 AM
 */

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class HotelRequests extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true; //
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            "name" => "required",
            "desc" => "required|string",
            "planet" => "not_in:-1",
            "stars"=>"not_in:-1",
            "pic" => "required|mimes:jpg,jpeg,gif,png|max:3000" // in KB
        ];
    }

    public function messages()
    {
        return [
            "required" => "Required field."
        ];
        //return parent::messages(); // TODO: Change the autogenerated stub
    }
}
